name: Build and Deploy to Azure Blob Storage
on:
  push:
    branches:
      - main  # Change this to your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version you need

      - name: Install dependencies
        run: yarn install

      - name: Ensure moment is installed
        run: yarn add moment

      - name: Increment version
        run: |
          VERSION=$(grep -oP 'const version = ref\("\K[0-9]+\.[0-9]+\.[0-9]+' src/layouts/MainLayout.vue)
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          sed -i "s/const version = ref('.*')/const version = ref('$NEW_VERSION')/" src/layouts/MainLayout.vue
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/layouts/MainLayout.vue
          git commit -m "Increment version to $NEW_VERSION"
          git push

      - name: Build the project
        run: yarn build

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -d '$web' -s dist --account-name geminiflowstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
